In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pip install tensorflow==2.11.0

In [ ]:
!pip install git+https://github.com/VenkateshwaranB/stellargraph.git

  Cloning https://github.com/VenkateshwaranB/stellargraph.git to /tmp/pip-req-build-vr74exoo
  Running command git clone --filter=blob:none --quiet https://github.com/VenkateshwaranB/stellargraph.git /tmp/pip-req-build-vr74exoo
  Resolved https://github.com/VenkateshwaranB/stellargraph.git to commit ce29510c83d924561c9e6054641d02a5abdeaaf5
  Preparing metadata (setup.py) ... done


In [ ]:
import networkx as nx
import stellargraph as sg

try:
    sg.utils.validate_notebook_version("1.2.1")
except AttributeError:
    raise ValueError(
        f"This notebook requires StellarGraph version 1.2.1, but a different version {sg.__version__} is installed.  Please see <https://github.com/stellargraph/stellargraph/issues/1172>."
    ) from None

<div class="alert alert-block alert-danger">This notebook is designed for an older StellarGraph version 1.2.1 and may not function correctly with the newer installed version 1.3.0b. Please see: <a href="https://github.com/stellargraph/stellargraph/issues/1172">https://github.com/stellargraph/stellargraph/issues/1172</a>.</div>

<ipython-input-4-670eaa390d98>:5: DeprecationWarning: This notebook is designed for an older StellarGraph version 1.2.1 and may not function correctly with the newer installed version 1.3.0b. Please see: <https://github.com/stellargraph/stellargraph/issues/1172>.
  sg.utils.validate_notebook_version("1.2.1")


In [ ]:
# If you have installed dgl-cuXX package, please uninstall it first.
!pip install  dgl -f https://data.dgl.ai/wheels/cu118/repo.html
!pip install  dglgo -f https://data.dgl.ai/wheels-test/repo.html

Looking in links: https://data.dgl.ai/wheels/cu118/repo.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 MB 8.7 MB/s eta 0:00:00
Looking in links: https://data.dgl.ai/wheels-test/repo.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.5/63.5 kB 3.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 6.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.2/45.2 kB 5.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.4/52.4 kB 5.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 kB 7.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 7.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.4/29.4 MB 46.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 4.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 118.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.6/485.6 kB 38.4 MB/s eta 0:00

In [ ]:
!pip install node2vec

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 35.3 MB/s eta 0:00:00
  Attempting uninstall: networkx
    Found existing installation: networkx 3.1
    Uninstalling networkx-3.1:
      Successfully uninstalled networkx-3.1


In [ ]:
import dgl
import torch
import torch.nn as nn
import dgl.nn.pytorch as dglnn
import os
os.environ["DGLBACKEND"] = "pytorch"
import numpy as np
import networkx as nx
import random
from typing import List
from tqdm import tqdm
from gensim.models.word2vec import Word2Vec
from node2vec import Node2Vec
import json

DGL backend not selected or invalid.  Assuming PyTorch for now.


Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)


In [ ]:
import torch
from dgl.data import CoraGraphDataset
from dgl.nn import DeepWalk
from torch.optim import SparseAdam
from torch.utils.data import DataLoader
from sklearn.linear_model import LogisticRegression

In [ ]:
(g,), _ = dgl.load_graphs('/content/drive/MyDrive/graph.dgl')
g

Graph(num_nodes=5186, num_edges=40662,
      ndata_schemes={}
      edata_schemes={})

In [ ]:
dataset = datasets.Cora()
display(HTML(dataset.description))
G, subjects = dataset.load(largest_connected_component_only=True)

In [ ]:
print(G.info())

StellarGraph: Undirected multigraph
 Nodes: 2485, Edges: 5209

 Node types:
  paper: [2485]
    Features: float32 vector, length 1433
    Edge types: paper-cites->paper

 Edge types:
    paper-cites->paper: [5209]
        Weights: all 1 (default)
        Features: none


In [ ]:
subjects.index

Int64Index([  31336, 1061127, 1106406,   13195,   37879, 1126012, 1107140,
            1102850,   31349, 1106418,
            ...
             767763,  152226,  152227, 1131180, 1128974, 1128975, 1128977,
            1128978,  117328,   24043],
           dtype='int64', length=2485)

In [ ]:
nx_graph = dgl.to_networkx(g)

In [ ]:
graph = sg.StellarGraph.from_networkx(nx_graph)

In [ ]:
graph.info()

'StellarDiGraph: Directed multigraph\n Nodes: 5186, Edges: 40662\n\n Node types:\n  default: [5186]\n    Features: none\n    Edge types: default-default->default\n\n Edge types:\n    default-default->default: [40662]\n        Weights: all 1 (default)\n        Features: none'

In [ ]:
import matplotlib.pyplot as plt

from sklearn.manifold import TSNE

import os
import networkx as nx
import numpy as np
import pandas as pd
from tensorflow import keras

from stellargraph import StellarGraph
from stellargraph.data import BiasedRandomWalk
from stellargraph.data import UnsupervisedSampler
from stellargraph.data import BiasedRandomWalk
from stellargraph.mapper import Node2VecLinkGenerator, Node2VecNodeGenerator
from stellargraph.layer import Node2Vec, link_classification

from stellargraph import datasets
from IPython.display import display, HTML

%matplotlib inline

In [ ]:
G = graph

In [ ]:
print(G.info())

StellarDiGraph: Directed multigraph
 Nodes: 5186, Edges: 40662

 Node types:
  default: [5186]
    Features: none
    Edge types: default-default->default

 Edge types:
    default-default->default: [40662]
        Weights: all 1 (default)
        Features: none


In [ ]:
walk_number = 100
walk_length = 5

In [ ]:
walker = BiasedRandomWalk(
    G,
    n=walk_number,
    length=walk_length,
    p=0.5,  # defines probability, 1/p, of returning to source node
    q=2.0,  # defines probability, 1/q, for moving to a node away from the source node
)

In [ ]:
unsupervised_samples = UnsupervisedSampler(G, nodes=list(G.nodes()), walker=walker)

In [ ]:
batch_size = 50
epochs = 2

In [ ]:
generator = Node2VecLinkGenerator(G, batch_size)

In [ ]:
emb_size = 128
node2vec = Node2Vec(emb_size, generator=generator)

In [ ]:
x_inp, x_out = node2vec.in_out_tensors()

In [ ]:
prediction = link_classification(
    output_dim=1, output_act="sigmoid", edge_embedding_method="dot"
)(x_out)

link_classification: using 'dot' method to combine node embeddings into edge embeddings


In [ ]:
model = keras.Model(inputs=x_inp, outputs=prediction)

model.compile(
    optimizer=keras.optimizers.Adam(lr=1e-3),
    loss=keras.losses.binary_crossentropy,
    metrics=[keras.metrics.binary_accuracy],
)

In [ ]:
history = model.fit(
    generator.flow(unsupervised_samples),
    epochs=epochs,
    verbose=1,
    use_multiprocessing=False,
    workers=4,
    shuffle=True,
)

Epoch 1/2
82976/82976 [==============================] - 1683s 20ms/step - loss: 0.1763 - binary_accuracy: 0.9162
Epoch 2/2
82976/82976 [==============================] - 1654s 20ms/step - loss: 0.0836 - binary_accuracy: 0.9719


In [ ]:
x_inp_src = x_inp[0]
x_out_src = x_out[0]
embedding_model = keras.Model(inputs=x_inp_src, outputs=x_out_src)

In [ ]:
G = graph
print(G.info())

StellarDiGraph: Directed multigraph
 Nodes: 5186, Edges: 40662

 Node types:
  default: [5186]
    Features: none
    Edge types: default-default->default

 Edge types:
    default-default->default: [40662]
        Weights: all 1 (default)
        Features: none


In [ ]:
G.nodes()

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            5176, 5177, 5178, 5179, 5180, 5181, 5182, 5183, 5184, 5185],
           dtype='int64', length=5186)

In [ ]:
node_gen = Node2VecNodeGenerator(G, batch_size).flow(series.index)
node_embeddings = embedding_model.predict(node_gen, workers=4, verbose=1)

104/104 [==============================] - 1s 4ms/step


In [ ]:
import numpy as np
np.shape(node_embeddings)

(5186, 128)

In [ ]:
transform = TSNE  # PCA

trans = transform(n_components=2)
node_embeddings_2d = trans.fit_transform(node_embeddings)

In [ ]:

import json

# Specify the path to your JSON file
json_file_path = '/content/drive/MyDrive/alias_2_id.json'

# Load the JSON file and parse it into a dictionary
with open(json_file_path, 'r') as file:
    json_data = file.read()
    alias_2_id = json.loads(json_data)

# Now you can use the 'dictionary' variable which contains the loaded data
print(alias_2_id)


{'0': '321631653', '1': '18655355', '2': '2467720274', '3': '3176702526', '4': '24939978', '5': '1646856415', '6': '2932942216', '7': '766475610059317248', '8': '2909998207', '9': '59621769', '10': '15537302', '11': '908585996', '12': '295731821', '13': '17564591', '14': '966354844754894848', '15': '19417492', '16': '803694179079458816', '17': '58007320', '18': '2353605901', '19': '117718572', '20': '875029068223315968', '21': '929766290323058688', '22': '35218566', '23': '2619593276', '24': '36711022', '25': '46756474', '26': '31059230', '27': '27194034', '28': '4124770811', '29': '2964174789', '30': '827641495125688321', '31': '69176047', '32': '956702734920564736', '33': '430106077', '34': '1309193942', '35': '2745534376', '36': '1015843266384859141', '37': '3241707920', '38': '3836645961', '39': '1696503140', '40': '477342040', '41': '890585748315000832', '42': '69004966', '43': '934859209279238148', '44': '19877186', '45': '775899392268177409', '46': '1254645558', '47': '960994743

In [ ]:
type(subjects)

pandas.core.series.Series

In [ ]:
nodes = []
for i in range(5186):
    nodes.append(int(alias_2_id[str(i)]))

In [ ]:
nodes

[321631653,
 18655355,
 2467720274,
 3176702526,
 24939978,
 1646856415,
 2932942216,
 766475610059317248,
 2909998207,
 59621769,
 15537302,
 908585996,
 295731821,
 17564591,
 966354844754894848,
 19417492,
 803694179079458816,
 58007320,
 2353605901,
 117718572,
 875029068223315968,
 929766290323058688,
 35218566,
 2619593276,
 36711022,
 46756474,
 31059230,
 27194034,
 4124770811,
 2964174789,
 827641495125688321,
 69176047,
 956702734920564736,
 430106077,
 1309193942,
 2745534376,
 1015843266384859141,
 3241707920,
 3836645961,
 1696503140,
 477342040,
 890585748315000832,
 69004966,
 934859209279238148,
 19877186,
 775899392268177409,
 1254645558,
 960994743357292544,
 15486485,
 792006970525880320,
 3095741260,
 784210425420316672,
 2483329075,
 346549154,
 407223771,
 733232251677364224,
 3124473681,
 727264708776980480,
 762327767295795200,
 1339835893,
 275139787,
 25073877,
 2547517884,
 1415709798,
 820354372827758592,
 1925388241,
 129235890,
 83739756,
 8780872803213352

In [ ]:
series = pd.Series(nodes)
series

0                321631653
1                 18655355
2               2467720274
3               3176702526
4                 24939978
               ...        
5181    899115298997055491
5182              23194229
5183    807692474684579840
5184              59213861
5185              26589498
Length: 5186, dtype: int64

In [ ]:
series.index

RangeIndex(start=0, stop=5186, step=1)

In [ ]:
adj_matrix = np.load('/content/drive/MyDrive/adj_matrix.npy')

In [ ]:
np.shape(adj_matrix)
adj_matrix

array([[1., 1., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
np.save('/content/drive/MyDrive/node_embeddings_node_2_vec_similarity.npy', node_embeddings)

In [ ]:
node_embeddings = np.load('/content/drive/MyDrive/node_embeddings_node_2_vec_similarity.npy')
np.shape(node_embeddings)

(5186, 128)

In [ ]:
positions = np.where(adj_matrix == 1)
positions

(array([   0,    0,    1, ..., 5184, 5185, 5185]),
 array([   0,    1,    0, ..., 5184,   13, 5185]))

In [ ]:
num_ones = np.count_nonzero(adj_matrix)
print(num_ones)

40662
